version: "3"
services:
  actual_server:
    container_name: actual_server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    volumes:
      - //f/Actual/server-files:/app/server-files
      - //f/Actual/user-files:/app/user-files
    restart: unless-stopped
